sudo: required
language: node_js
cache:
  yarn: true
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - docker
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV="test"
node_js:
  - "8"
before_script:
  - docker-compose up
script:
  - cd backend && make lint
  - cd frontend && npm run pretest
