sudo: required
language: node_js
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - docker
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV="test"
node_js:
  - "8"
before_script:
  - make docker
  - cd backend && yarn install
  - cd frontend && yarn install
script:
  - cd backend && make lint
  - cd frontend && npm run pretest
